### PR TITLE
support analysis from spreadsheet URL

### PR DESCRIPTION
**Pull request by targos**
It is not ready yet. I'm opening this to ask an important question :)

@Trott It seems that the input for this script is not the spreadsheet itself. Do you process it before running the script?

### CODE REVIEW

**Comment by Trott** [comment]
I highlight the cells that contain the ratings and copy/paste them into a file. They are tab-separated by default when I do that, which is why the input file is .tsv. I think @ChALkeR figured that out/set that up.

**Comment by targos** [comment]
I think I got it. Is this the correct result?

```
{ times: [ 7, 16, 21 ], standardDeviation: 0.3316265828853147 }
{ times: [ 12, 17, 23 ], standardDeviation: 0.3355343996274202 }
{ times: [ 12, 17, 22 ], standardDeviation: 0.3414430162316011 }
{ times: [ 12, 19, 22 ], standardDeviation: 0.3437191544602323 }
{ times: [ 12, 15, 22 ], standardDeviation: 0.3521870444603467 }
```

**Comment by Trott** [comment]
Oh, so to answer the question: No, no pre-processing.

**Comment by targos** [comment]
(with the default options)

**Comment by Trott** [comment]
> I think I got it. Is this the correct result?

Hmmm, no, that doesn't look correct. With the current spreadsheet data, I get this:

```console
$ node index.js 
{ times: [ 13, 15, 22 ], standardDeviation: 0.4832183771339829 }
{ times: [ 13, 15, 23 ],
  standardDeviation: 0.48536927522591844 }
{ times: [ 13, 16, 23 ], standardDeviation: 0.5017469481720841 }
{ times: [ 13, 16, 22 ], standardDeviation: 0.5087566543381358 }
{ times: [ 15, 19, 23 ], standardDeviation: 0.5203707469542406 }
$ 
```

**Comment by Trott** [comment]
If it helps, I'm copy/pasting 3B on the top left to 23Y on the lower right.

**Comment by Trott** [comment]
(Also: Those results are different than the current time slots/proposal because it includes someone who plans to become Emeritus soon. I do manually delete their row before running, normally, but didn't do that above.)

**Comment by targos** [comment]
I get the same result by copy/pasting this range on this branch and on master...

**Comment by targos** [comment]
(I mean the same as I posted before)

**Comment by Trott** [comment]
> I get the same result by copy/pasting this range on this branch and on master...

My mistake! I was running with code I had slightly modified. Sorry about that. Yes, those results look correct.

**Comment by targos** [comment]
just added a readme to explain how the spreadsheet url is constructed

**Review by Trott — APPROVED** [review]
🎉

**Pull request merged**
